#!/bin/sh -e

#20121128
#Jan Mojzis
#Public domain.

[ -f do-tarbz2 ] || (echo "file do-tarbz2 not found"; exit 111;)
[ -f conf-home ] || (echo "file conf-home not found"; exit 111;)
[ -f conf-version ] || (echo "file conf-version not found"; exit 111;)

curveprotectdir=`head -1 conf-home`
version=`head -1 conf-version`
build="`pwd`/build"
rm -rf "${build}/curveprotect-${version}"
mkdir -p "${build}/curveprotect-${version}"

files=""
for f in `ls | sort`; do
  [ x"${f}" = xbuild ] && continue
  files="${files} ${f}"
done
cp -pr ${files} "${build}/curveprotect-${version}"
(
  cd "${build}"
  tar cf - "curveprotect-${version}" | bzip2 > "curveprotect-${version}.tar.bz2.tmp"
  mv -f "curveprotect-${version}.tar.bz2.tmp" "curveprotect-${version}.tar.bz2"
  rm -rf "curveprotect-${version}"
)
